[build-system]
requires = [
    "setuptools>=65.3.0",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest tests"

[tool.pytest.ini_options]
pythonpath = "."
