from typing import ClassVar

Execute: Flags
Read: Flags
Write: Flags
__version__: str

class Flags:
    __members__: ClassVar[dict] = ...  # read-only
    Execute: ClassVar[Flags] = ...
    Read: ClassVar[Flags] = ...
    Write: ClassVar[Flags] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def add(i: int, j: int) -> int: ...
def sub(i: int, j: int) -> int: ...
