name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and test package
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"
      - name: Build package
        run: |
          poe build
      - name: Check linting
        run: |
          poe lint
      - name: Test package
        run: |
          coverage run -m pytest
          echo "# Python coverage report" >> $GITHUB_STEP_SUMMARY
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY || true
