name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"
      - name: Test with pytest
        run: |
          poe build
          poe test
