name: Build

on: [push, pull_request]

jobs:

  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.1
        env:
          # python39 only
          CIBW_BUILD: cp39-*
          # no pypy, win32, linux32
          CIBW_SKIP: "pp* *-win32 *_i686"
          # universal mac wheels
          CIBW_ARCHS_MACOS: "universal2"
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
